version: build.{build}
image: Visual Studio 2017
matrix:
  fast_finish: true
environment:
  FREETYPE_VER: 2.10.1
  VS_CXXFLAGS: /DWIN32 /D_WINDOWS /W4 /GR /EHsc /permissive- /w44062
  RUN_MINGW: false
  matrix:
    - RUN_MINGW: true
    - VS_GENERATOR: Visual Studio 15 2017 Win64
      PLATFORM_NAME: win64
    - VS_GENERATOR: Visual Studio 15 2017
      PLATFORM_NAME: win32
install:
- cmd: |-
    cd Dependencies

    appveyor DownloadFile https://github.com/ubawurinna/freetype-windows-binaries/releases/download/v%FREETYPE_VER%/freetype.zip
    unzip -o freetype.zip -d freetype_tmp
    mv freetype_tmp/include include
    mv freetype_tmp/%PLATFORM_NAME% lib
    
    cd ..
    mkdir Build-Dynamic, Build-Static
    
    cd Build-Dynamic
    cmake -G "%VS_GENERATOR%" -DBUILD_SHARED_LIBS=ON -DBUILD_SAMPLES=ON -DCMAKE_CXX_FLAGS="%VS_CXXFLAGS%" ..

    cd ../Build-Static
    cmake -G "%VS_GENERATOR%" -DBUILD_SHARED_LIBS=OFF -DBUILD_SAMPLES=OFF ..
    
    cd ..
    
build_script:
- cmd: |-
    msbuild Build-Dynamic/RmlUi.sln /p:configuration=debug   /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    msbuild Build-Dynamic/RmlUi.sln /p:configuration=release /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    msbuild Build-Static/RmlUi.sln  /p:configuration=debug   /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    msbuild Build-Static/RmlUi.sln  /p:configuration=release /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
after_build:
- cmd: |-
    mkdir Bin
    cd Bin
    mkdir Dynamic-Debug, Dynamic-Release, Static-Debug, Static-Release
    cp ../Build-Dynamic/Debug/Rml*.{lib,dll,pdb} Dynamic-Debug
    cp ../Build-Dynamic/Release/Rml*.{lib,dll} Dynamic-Release
    cp ../Build-Static/Debug/Rml*.{lib,pdb} Static-Debug
    cp ../Build-Static/Release/Rml*.lib Static-Release
    cd ..
    
    cp Build-Dynamic/Release/*.exe Samples
    cp Bin/Dynamic-Release/*.dll Samples
    cp Dependencies/lib/*.dll Samples

    mv Dependencies/lib/ Dependencies/freetype-%FREETYPE_VER%
    cp Dependencies/freetype_tmp/*.TXT Dependencies/freetype-%FREETYPE_VER%
    
    IF NOT "%APPVEYOR_REPO_TAG_NAME%"=="" SET RMLUI_VERSION= %APPVEYOR_REPO_TAG_NAME%
    
    echo RmlUi%RMLUI_VERSION% library and sample binaries for %PLATFORM_NAME%.> Readme.txt& echo.>>Readme.txt
    echo https://github.com/mikke89/RmlUi>> Readme.txt& echo.>>Readme.txt
    echo Built using %VS_GENERATOR% on %APPVEYOR_REPO_COMMIT_TIMESTAMP:~0,10% (build %APPVEYOR_BUILD_NUMBER%).>> Readme.txt
    echo Commit id: %APPVEYOR_REPO_COMMIT%.>> Readme.txt
    
    7z a RmlUi-%PLATFORM_NAME%.zip Bin/ Include/ Readme.txt changelog.md LICENSE Dependencies/freetype-%FREETYPE_VER%/ Samples/
    
    mkdir Samples\Dependencies\freetype-%FREETYPE_VER%
    cp Dependencies/freetype-%FREETYPE_VER%/*.TXT Samples/Dependencies/freetype-%FREETYPE_VER%
    IF "%PLATFORM_NAME%"=="win64" 7z a RmlUi-%PLATFORM_NAME%-samples-only.zip LICENSE .\Samples\* -r -xr!src\ -x!shell\ -x!luainvaders\
    
for:
-
  matrix:
    only:
      - RUN_MINGW: true
  install:
  - cmd: |-
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-gcc"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-make"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-freetype"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-sfml"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-lua"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-SDL2"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-SDL2_image"
      C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-glew"
      
      mkdir Build
      cd Build
      
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
      set GLEW_INCLUDE_DIR=C:/msys64/mingw64/include/GL
      set GLEW_LIBRARIES=C:/msys64/mingw64/lib/libglew32.dll.a
      
      cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_SAMPLES=ON -DBUILD_LUA_BINDINGS=ON -DCMAKE_C_COMPILER=gcc.exe -DCMAKE_CXX_COMPILER=g++.exe -DCMAKE_MAKE_PROGRAM=mingw32-make.exe -DGLEW_INCLUDE_DIR=%GLEW_INCLUDE_DIR% -DGLEW_LIBRARIES=%GLEW_LIBRARIES% ..

      set CHERE_INVOKING=yes
      set MSYSTEM=MINGW64

  build_script:
  - cmd: |-
      C:\msys64\usr\bin\bash -lc "mingw32-make.exe -j4"
      
  after_build:
  - cmd: |-
      ls {*.exe,*.dll} -s -h -X

artifacts:
- path: RmlUi-win64.zip
- path: RmlUi-win64-samples-only.zip
- path: RmlUi-win32.zip
deploy:
  release: RmlUi $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: g/WlXrOszpqKYC++IvUvNOPhuEeHbMm+2/TWzcgQko+nIGKmjvfAWUxouNhgsUy9
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
    RUN_MINGW: false
